// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartupProjects
{
    static class Vsix
    {
        public const string Id = "00302942-1ef6-4dcd-b25c-a82e02a661f9";
        public const string Name = "Startup Projects";
        public const string Description = "The easiest way to add/remove project to a startup projects directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Themba Masina";
        public const string Tags = "startup, projects";
    }
}
