// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartupProjects
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddToStartupProjectCommandPackageString = "a6f62261-b200-41f4-8827-3ce7ff087848";
        public const string guidAddToStartupProjectCommandPackageCmdSetString = "6aab571c-daed-43f3-9581-0e86325885b7";
        public const string guidImagesString = "125ef172-90ee-4b13-9246-9b8af2316482";
        public static Guid guidAddToStartupProjectCommandPackage = new Guid(guidAddToStartupProjectCommandPackageString);
        public static Guid guidAddToStartupProjectCommandPackageCmdSet = new Guid(guidAddToStartupProjectCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AddToStartupProjectCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
